# Generated by Django 5.2.1 on 2025-06-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_franchiseinquiry_delete_servicerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseinquiry',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='workinquiry',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
